site_name: OpenRISC MiddleWare Libraries
site_description: 'The manual of the OpenRISC libraries'
site_author: 'Philip Park'

# Repository
site_url: https://jhpark555.github.io/newdocu
repo_url: https://github.com/jhpark555/newdocu

pages:
 - 'Introduction': 'index.md'
 - 'Code Structure': 'code.md'
 - 'FreeRTOS': 'FreeRTOS.md'
 
# - API : 'docs/html/index.html'
 
theme:
 name: amelia
# name: journal
# name: readable
# name: 'material'
# name: 'readthedocs'


# Copyright
copyright: 'Copyright & copy; 2018 Philip Park'
google_analytics: ['UA-36723568-3', 'mkdocs.org']
